"""Multi-vendor O1 framework — Wave 9 (HISTORY.md W9-01..06),
building `docs/ARCHITECTURE.md`'s sketch.

Onboarding a vendor is data, not code:

  * **Capability Registry** (W9-01/W9-04) — `PUT /vendor-capabilities/{vendor}`:
    the MnS services the vendor's O1 terminations implement (axis 2, a
    presence list), its data-model conformance (axis 3: `OWN` / `SPEC` /
    `COMBINED`, with `schemaRef` = the vendor's own descriptor and
    `specSchemaRef` = the spec descriptor), and the O1 transports it speaks
    (`supportedVendorModes`: `O1_NETCONF` / `O1_RESTCONF`).
  * **CM schema descriptors** (W9-02) — `POST /cm-schemas`: `CMSchemaCache`
    finally gets a writer and a reader. A descriptor (`{"classes": {IOC:
    {attribute: {type, enum?}}}}`) is generated by
    `scripts/ingest_cm_schema.py`; the 3GPP TS 28.541 NR NRM one is bundled
    (`app/cm_schemas/`) as the default spec descriptor.
  * **Vendor onboarding** (W9-03) — `POST /vendor-onboarding`: discover the
    vendor's declared capabilities from its adaptor, load its schema(s),
    declare its capability, in one call. Endpoints then register through the
    unchanged `POST /o1-adaptor-endpoints` with `vendorName`.

Two generic checks read the registry at request time — no per-vendor
branching anywhere: `require_service` (an ME whose vendor doesn't implement
FM/PM/SWM/PROV is refused before anything is created) and
`schema_problems` (a CM write is checked against the descriptor(s) its
vendor's conformance mode selects). An ME with no vendor capability
registered skips both, the permissive default the guide specifies.

Cell guard attributes (W9-06, decision D-5) live on `ManagedEntity` and are
queryable by any rApp (`GET /cell-guards`).
"""

import datetime
import json
from functools import lru_cache
from pathlib import Path
from typing import Literal
from urllib.parse import urlsplit, urlunsplit

from fastapi import APIRouter, Depends, Query, Request
from pydantic import BaseModel, ConfigDict, Field, field_validator
from sqlalchemy import func, select
from sqlalchemy.orm import Session

from smo_shared.db import get_session
from smo_shared.errors import FrameworkError, framework_error
from smo_shared import scope as authz_scope
from smo_shared.pagination import PageLimit, PageOffset, paginate, paginate_list
from smo_shared.webhook import get_webhook

from . import msac, scoping
from .ldn import leaf_class
from .leafcheck import check_value
from .models import CMSchemaCache, ManagedEntity, O1AdaptorEndpoint, VendorCapability

router = APIRouter()

MnsService = Literal["PROV", "FM", "PM", "FILE", "STREAM", "SWM", "SUBSCRIPTION", "HEARTBEAT"]
MNS_SERVICES = ["PROV", "FM", "PM", "FILE", "STREAM", "SWM", "SUBSCRIPTION", "HEARTBEAT"]
VendorMode = Literal["O1_NETCONF", "O1_RESTCONF"]
ConformanceMode = Literal["OWN", "SPEC", "COMBINED"]
CellClass = Literal["EMERGENCY", "COVERAGE_CRITICAL", "NORMAL"]
# ManagedEntity.o1_protocol -> the vendor mode it needs
PROTOCOL_MODE = {"NETCONF": "O1_NETCONF", "RESTCONF": "O1_RESTCONF"}

_BUILTIN_DIR = Path(__file__).parent / "cm_schemas"
DEFAULT_SPEC_SCHEMA = ("3gpp-ts28541-nrnrm", "19.6.0")


@lru_cache
def _builtin_schemas() -> dict[tuple[str, str], dict]:
    """The descriptors bundled in `app/cm_schemas/*.json`, keyed by (schemaName, revision) and marked `builtin:<file>` as their location. Read once per process.
    """
    out = {}
    for path in sorted(_BUILTIN_DIR.glob("*.json")):
        d = json.loads(path.read_text())
        out[(d["schemaName"], d["revision"])] = {**d, "location": f"builtin:{path.name}"}
    return out


# ---------------------------------------------------------------- schemas (W9-02)

# Reference to a CM schema by name and revision (an empty revision is a valid revision value). Part of the capability request bodies.
class SchemaRef(BaseModel):
    model_config = ConfigDict(extra="forbid")
    schemaName: str
    revision: str = ""


# Request body of `POST /cm-schemas`: the descriptor to load and its identity. See `scripts/ingest_cm_schema.py` for how a descriptor is generated.
class CMSchemaBody(BaseModel):
    model_config = ConfigDict(extra="forbid")
    schemaName: str
    revision: str = ""
    type: Literal["YANG", "OPENAPI_NRM", "DESCRIPTOR"] = "DESCRIPTOR"
    location: str
    descriptor: dict = Field(description='{"classes": {"<IOC>": {"<attribute>": {"type": ..., "enum"?: [...]}}}}')


def _check_descriptor(descriptor: dict) -> None:
    classes = descriptor.get("classes")
    if not isinstance(classes, dict) or not all(isinstance(a, dict) for a in classes.values()):
        raise framework_error(FrameworkError.SCHEMA_VALIDATION_FAILED,
                              detail='descriptor must be {"classes": {IOC: {attribute: {...}}}}')


def _schema_view(name: str, revision: str, type_: str, location: str, descriptor: dict | None, builtin: bool,
                 full: bool = False) -> dict:
    """The JSON view of a schema: identity, type, location, whether it is bundled and its class count; the descriptor itself only when `full`."""
    classes = (descriptor or {}).get("classes", {})
    view = {"schemaName": name, "revision": revision, "type": type_, "location": location, "builtin": builtin,
            "classCount": len(classes)}
    if full:
        view["descriptor"] = descriptor
    return view


def _descriptor(db: Session, name: str | None, revision: str | None) -> dict | None:
    """The class descriptor of a schema by name and revision: a loaded one (`cm_schema_cache`) wins over a bundled one of the same key; None when `name` is empty or neither exists.
    """
    if not name:
        return None
    row = db.get(CMSchemaCache, (name, revision or ""))
    if row is not None:
        return row.descriptor
    builtin = _builtin_schemas().get((name, revision or ""))
    return builtin and {"classes": builtin["classes"]}


def _require_schema(db: Session, ref: SchemaRef | None) -> None:
    if ref is not None and _descriptor(db, ref.schemaName, ref.revision) is None:
        raise framework_error(FrameworkError.CM_SCHEMA_NOT_FOUND, detail=f"no CM schema {ref.schemaName}@{ref.revision}")


def _load_schema(db: Session, body: CMSchemaBody) -> tuple[dict, bool]:
    """Creates the schema; an identical one already loaded is reused."""
    _check_descriptor(body.descriptor)
    key = (body.schemaName, body.revision)
    existing = db.get(CMSchemaCache, key)
    if existing is not None or key in _builtin_schemas():
        current = existing.descriptor if existing is not None else {"classes": _builtin_schemas()[key]["classes"]}
        if (current or {}).get("classes") != body.descriptor.get("classes"):
            raise framework_error(FrameworkError.CM_SCHEMA_CONFLICT,
                                  detail=f"{body.schemaName}@{body.revision} is already loaded with a different descriptor")
        return {"schemaName": body.schemaName, "revision": body.revision}, False
    db.add(CMSchemaCache(schema_name=body.schemaName, revision=body.revision, location=body.location, type=body.type,
                         descriptor={"classes": body.descriptor["classes"]}))
    db.flush()
    return {"schemaName": body.schemaName, "revision": body.revision}, True


@router.post("/cm-schemas", status_code=201)
def load_cm_schema(body: CMSchemaBody, db: Session = Depends(get_session)):
    # 422 SCHEMA_VALIDATION_FAILED for a descriptor without a `classes` map; 409 CM_SCHEMA_CONFLICT when the name and revision are already loaded (even with an identical descriptor, here; `POST /vendor-onboarding` reuses an identical one instead) or are a bundled schema. 201 with the stored schema (descriptor not echoed).
    ref, created = _load_schema(db, body)
    if not created:
        raise framework_error(FrameworkError.CM_SCHEMA_CONFLICT, detail=f"{ref['schemaName']}@{ref['revision']} is already loaded")
    db.commit()
    row = db.get_one(CMSchemaCache, (body.schemaName, body.revision))
    return _schema_view(row.schema_name, row.revision, row.type, row.location, row.descriptor, builtin=False)


def _visible_schema_keys(db: Session, scope: authz_scope.Scope | None) -> set[tuple[str, str]] | None:
    """PR-SEC-10.9: the loaded CM schemas a caller with a scope claim may read, as (name, revision): the ones the capability entries of its elements' vendors name (the
    vendor's own and the spec one). `None`: every one (an unscoped caller). The schemas bundled with the service are the 3GPP and O-RAN models, the same for every
    deployment and about no element, and are shown to every caller."""
    if scope is None:
        return None
    caps = db.scalars(select(VendorCapability).where(VendorCapability.vendor_name.in_(scoping.visible_vendor_names(scope)))).all()
    keys: set[tuple[str, str]] = set()
    for cap in caps:
        if cap.schema_name:
            keys.add((cap.schema_name, cap.schema_revision or ""))
        if cap.spec_schema_name:
            keys.add((cap.spec_schema_name, cap.spec_schema_revision or ""))
    return keys


@router.get("/cm-schemas")
def list_cm_schemas(request: Request, limit: int = PageLimit, offset: int = PageOffset, db: Session = Depends(get_session)):
    """The CM schemas, the ones bundled with the service and the ones loaded. PR-SEC-10.9: a caller with a scope claim sees the loaded ones its elements' vendors use."""
    visible = _visible_schema_keys(db, scoping.request_scope(request))
    rows = [_schema_view(r.schema_name, r.revision, r.type, r.location, r.descriptor, builtin=False)
            for r in db.scalars(select(CMSchemaCache).order_by(CMSchemaCache.schema_name, CMSchemaCache.revision))
            if visible is None or (r.schema_name, r.revision) in visible]
    builtins = [_schema_view(n, rev, d["type"], d["location"], d, builtin=True) for (n, rev), d in _builtin_schemas().items()]
    return paginate_list(builtins + rows, limit, offset)


@router.get("/cm-schemas/{schema_name}")
def get_cm_schema(schema_name: str, request: Request, revision: str = "", db: Session = Depends(get_session)):
    """One schema with its descriptor. PR-SEC-10.9: a loaded schema that is not one of a caller's elements' vendors is a 404 for a caller with a scope claim (a bundled
    schema of the same name and revision, when there is one, is shown in its place)."""
    visible = _visible_schema_keys(db, scoping.request_scope(request))
    row = db.get(CMSchemaCache, (schema_name, revision))
    if row is not None and (visible is None or (schema_name, revision) in visible):
        return _schema_view(row.schema_name, row.revision, row.type, row.location, row.descriptor, builtin=False, full=True)
    builtin = _builtin_schemas().get((schema_name, revision))
    if builtin is None:
        raise framework_error(FrameworkError.CM_SCHEMA_NOT_FOUND, detail=f"no CM schema {schema_name}@{revision}")
    return _schema_view(schema_name, revision, builtin["type"], builtin["location"], {"classes": builtin["classes"]},
                        builtin=True, full=True)


# ---------------------------------------------------------------- capability registry (W9-01, W9-04)

# Request body of `PUT /vendor-capabilities/{vendor}`: the MnS services, the conformance mode and the schemas it refers to, and the O1 transports. `schemaRef` is required for OWN and COMBINED.
class VendorCapabilityBody(BaseModel):
    model_config = ConfigDict(extra="forbid")
    supportedServices: list[MnsService] = Field(min_length=1)
    conformanceMode: ConformanceMode = "SPEC"
    supportedVendorModes: list[VendorMode] = Field(default=["O1_NETCONF"], min_length=1)
    schemaRef: SchemaRef | None = None       # the vendor's own descriptor (OWN / COMBINED)
    specSchemaRef: SchemaRef | None = None   # the spec descriptor (SPEC / COMBINED); default: bundled TS 28.541


def _capability_view(c: VendorCapability) -> dict:
    """The JSON view of a capability entry, with its schema references as objects and `updatedAt` as ISO text."""
    return {
        "vendorName": c.vendor_name, "supportedServices": c.supported_services, "conformanceMode": c.conformance_mode,
        "supportedVendorModes": c.supported_vendor_modes,
        "schemaRef": {"schemaName": c.schema_name, "revision": c.schema_revision or ""} if c.schema_name else None,
        "specSchemaRef": {"schemaName": c.spec_schema_name, "revision": c.spec_schema_revision or ""} if c.spec_schema_name else None,
        "discoveryUri": c.discovery_uri, "updatedAt": c.updated_at.isoformat(),
    }


def _declare_capability(db: Session, vendor_name: str, body: VendorCapabilityBody,
                        discovery_uri: str | None = None) -> VendorCapability:
    """Creates or replaces the capability entry of `vendor_name` in the caller's transaction (flushed, not committed). 422 SCHEMA_VALIDATION_FAILED when OWN or COMBINED has no `schemaRef`; 404 CM_SCHEMA_NOT_FOUND when a referenced schema is not loaded or bundled. A SPEC or COMBINED entry with no `specSchemaRef` gets the bundled TS 28.541 descriptor. Every managed element of the vendor is then re-checked against the new modes (`check_vendor_mode`), so a declaration that would strand a registered element is refused and, since the caller does not commit, not kept.
    """
    if body.conformanceMode in ("OWN", "COMBINED") and body.schemaRef is None:
        raise framework_error(FrameworkError.SCHEMA_VALIDATION_FAILED,
                              detail=f"conformanceMode {body.conformanceMode} needs schemaRef (the vendor's own descriptor)")
    spec_ref = body.specSchemaRef
    if spec_ref is None and body.conformanceMode in ("SPEC", "COMBINED"):
        spec_ref = SchemaRef(schemaName=DEFAULT_SPEC_SCHEMA[0], revision=DEFAULT_SPEC_SCHEMA[1])
    _require_schema(db, body.schemaRef)
    _require_schema(db, spec_ref)
    cap = db.get(VendorCapability, vendor_name) or VendorCapability(vendor_name=vendor_name)
    cap.supported_services = sorted(set(body.supportedServices), key=MNS_SERVICES.index)
    cap.conformance_mode = body.conformanceMode
    cap.supported_vendor_modes = sorted(set(body.supportedVendorModes))
    cap.schema_name = body.schemaRef.schemaName if body.schemaRef else None
    cap.schema_revision = body.schemaRef.revision if body.schemaRef else None
    cap.spec_schema_name = spec_ref.schemaName if spec_ref else None
    cap.spec_schema_revision = spec_ref.revision if spec_ref else None
    cap.discovery_uri = discovery_uri
    cap.updated_at = datetime.datetime.now(datetime.UTC)
    db.add(cap)
    db.flush()
    # every endpoint already registered for this vendor must use a declared mode
    for me in db.scalars(select(ManagedEntity).where(ManagedEntity.vendor_name == vendor_name)):
        check_vendor_mode(db, vendor_name, me.o1_protocol)
    return cap


@router.put("/vendor-capabilities/{vendor_name}")
def declare_vendor_capability(vendor_name: str, body: VendorCapabilityBody, db: Session = Depends(get_session)):
    # Create or replace; 200 with the entry. Errors as `_declare_capability`: 422, 404 CM_SCHEMA_NOT_FOUND, 409 PROTOCOL_NOT_SUPPORTED when a registered element of the vendor uses a mode the new declaration drops. Commits.
    cap = _declare_capability(db, vendor_name, body)
    db.commit()
    return _capability_view(cap)


def _vendor_capabilities(scope: authz_scope.Scope | None):
    """The capability entries a caller may read: every one for an unscoped caller; for one with a scope claim (PR-SEC-10.9) the entries of the vendors of its own
    elements. The registry has no element, region or tenant of its own, so this is derived: an entry that no element in the caller's scope uses is not shown."""
    stmt = select(VendorCapability)
    return stmt if scope is None else stmt.where(VendorCapability.vendor_name.in_(scoping.visible_vendor_names(scope)))


@router.get("/vendor-capabilities")
def list_vendor_capabilities(request: Request, limit: int = PageLimit, offset: int = PageOffset, db: Session = Depends(get_session)):
    # Paged, ordered by vendor name. A caller with a scope claim sees only the vendors of its own elements.
    page = paginate(db, _vendor_capabilities(scoping.request_scope(request)).order_by(VendorCapability.vendor_name), limit, offset)
    return {**page, "items": [_capability_view(c) for c in page["items"]]}


@router.get("/vendor-capabilities/{vendor_name}")
def get_vendor_capability(vendor_name: str, request: Request, db: Session = Depends(get_session)):
    """One vendor's capability entry. PR-SEC-10.9: for a caller with a scope claim, 404 when none of its elements is of that vendor, as if there were no entry."""
    cap = db.scalars(_vendor_capabilities(scoping.request_scope(request)).where(VendorCapability.vendor_name == vendor_name)).one_or_none()
    if cap is None:
        raise framework_error(FrameworkError.VENDOR_CAPABILITY_NOT_FOUND, detail=f"no capability registered for vendor {vendor_name!r}")
    return _capability_view(cap)


@router.delete("/vendor-capabilities/{vendor_name}", status_code=204)
def delete_vendor_capability(vendor_name: str, request: Request, db: Session = Depends(get_session)):
    # 204 whether or not the entry existed. Elements of the vendor stay registered and are then unchecked (no entry means the permissive default).
    # SEC-15.7: filtered by scope as the get is: a caller with a scope claim can delete only the entry of a vendor one of its own elements uses; any other entry is left alone and
    # the 204 says nothing, as when a subscription outside the scope is unsubscribed (the answer must not tell it which vendors exist). An unscoped caller is not asked.
    cap = db.scalars(_vendor_capabilities(scoping.request_scope(request)).where(VendorCapability.vendor_name == vendor_name)).one_or_none()
    if cap is not None:
        db.delete(cap)
        db.commit()


@router.get("/capabilities")
def o1_capabilities(request: Request, db: Session = Depends(get_session)):
    """What this RAN NF OAM can drive across every registered vendor —
    `supportedVendorModes` is the union of the vendors' declared modes. PR-SEC-10.9: for a caller with a scope claim, across the vendors of its own elements."""
    caps = db.scalars(_vendor_capabilities(scoping.request_scope(request))).all()
    return {"supportedVendorModes": sorted({m for c in caps for m in c.supported_vendor_modes}),
            "mnsServices": MNS_SERVICES,
            "vendors": [{"vendorName": c.vendor_name, "supportedVendorModes": c.supported_vendor_modes,
                         "supportedServices": c.supported_services, "conformanceMode": c.conformance_mode} for c in caps]}


# ---------------------------------------------------------------- vendor onboarding flow (W9-03)

# Request body of `POST /vendor-onboarding`. Values given here win over what discovery returns; `discoverFrom` names an element already registered for the vendor.
class VendorOnboardingBody(BaseModel):
    model_config = ConfigDict(extra="forbid")
    vendorName: str
    # A managed element already registered for this vendor (POST
    # /o1-adaptor-endpoints): its adaptor's capability declaration is read.
    discoverFrom: str | None = None
    supportedServices: list[MnsService] | None = None
    supportedVendorModes: list[VendorMode] | None = None
    conformanceMode: ConformanceMode = "SPEC"
    schemas: list[CMSchemaBody] = []
    schemaRef: SchemaRef | None = None
    specSchemaRef: SchemaRef | None = None


def _registered_discovery_uri(db: Session, managed_element_ref: str, vendor_name: str) -> str:
    """The URL of the capability declaration of the adaptor registered for an element: `/capabilities` on that adaptor's origin, never a URL from the request (no request-supplied host is ever contacted). Errors: the element is unknown (404 MANAGED_ENTITY_NOT_FOUND), registered for another vendor (422), has no adaptor endpoint (503 ENDPOINT_UNREACHABLE) or is not an HTTP adaptor (PROTOCOL_NOT_SUPPORTED, discovery is an HTTP GET).
    """
    me = _get_me(db, managed_element_ref)
    if me.vendor_name != vendor_name:
        raise framework_error(FrameworkError.SCHEMA_VALIDATION_FAILED,
                              detail=f"{managed_element_ref} is registered for vendor {me.vendor_name!r}, not {vendor_name!r}")
    endpoint = db.get(O1AdaptorEndpoint, me.o1_adaptor_endpoint_id) if me.o1_adaptor_endpoint_id else None
    if endpoint is None:
        raise framework_error(FrameworkError.ENDPOINT_UNREACHABLE, detail=f"{managed_element_ref} has no registered O1 adaptor")
    if endpoint.transport != "http-mock":
        raise framework_error(FrameworkError.PROTOCOL_NOT_SUPPORTED,
                              detail=f"capability discovery is an HTTP GET; {managed_element_ref} is reached over {endpoint.transport}")
    origin = urlsplit(endpoint.adaptor_uri)
    return urlunsplit((origin.scheme, origin.netloc, "/capabilities", "", ""))


@router.post("/vendor-onboarding", status_code=201)
def onboard_vendor(body: VendorOnboardingBody, db: Session = Depends(get_session)):
    """Endpoint discovery → capability declaration → schema load, as one
    call (call flow 21). Values given in the body win over discovered ones.

    Discovery only ever contacts an adaptor already in this module's own
    endpoint registry — the one CM writes are sent to anyway — never a URL
    taken from the request: its declaration is read at the fixed path
    `/capabilities` on that adaptor's registered origin.
    """
    # Order: discover (when `discoverFrom`), load the listed schemas (an identical one already loaded is reused, a different one under the same key is 409), declare the capability, commit once. A failure at any step leaves nothing persisted. 201 with the discovered declaration, the schemas (`created` per schema) and the entry. Errors: 503 ENDPOINT_UNREACHABLE when discovery fails, 422 when the adaptor names another vendor or no services are given or discoverable.
    discovered = discovery_uri = None
    if body.discoverFrom:
        discovery_uri = _registered_discovery_uri(db, body.discoverFrom, body.vendorName)
        resp = get_webhook(discovery_uri)
        if resp is None or resp.status_code != 200:
            raise framework_error(FrameworkError.ENDPOINT_UNREACHABLE, detail=f"capability discovery at {discovery_uri} failed")
        discovered = resp.json()
        if discovered.get("vendorName") not in (None, body.vendorName):
            raise framework_error(FrameworkError.SCHEMA_VALIDATION_FAILED,
                                  detail=f"adaptor declares vendor {discovered['vendorName']!r}, not {body.vendorName!r}")
    services = body.supportedServices or (discovered or {}).get("supportedServices")
    modes = body.supportedVendorModes or (discovered or {}).get("supportedVendorModes") or ["O1_NETCONF"]
    if not services:
        raise framework_error(FrameworkError.SCHEMA_VALIDATION_FAILED,
                              detail="supportedServices must be given or discoverable from the vendor's adaptor")

    loaded = [{**ref, "created": created} for ref, created in (_load_schema(db, s) for s in body.schemas)]
    schema_ref = body.schemaRef
    if schema_ref is None and body.conformanceMode in ("OWN", "COMBINED") and len(body.schemas) == 1:
        schema_ref = SchemaRef(schemaName=body.schemas[0].schemaName, revision=body.schemas[0].revision)
    cap = _declare_capability(db, body.vendorName, VendorCapabilityBody(
        supportedServices=services, conformanceMode=body.conformanceMode, supportedVendorModes=modes,
        schemaRef=schema_ref, specSchemaRef=body.specSchemaRef), discovery_uri=discovery_uri)
    db.commit()
    return {"vendorName": body.vendorName, "discovered": discovered, "schemasLoaded": loaded,
            "capability": _capability_view(cap)}


# ---------------------------------------------------------------- the two generic checks

def vendor_capability(db: Session, me: ManagedEntity | None) -> VendorCapability | None:
    return db.get(VendorCapability, me.vendor_name) if me is not None and me.vendor_name else None


def effective_services(db: Session, me: ManagedEntity | None) -> list[str] | None:
    """The endpoint's own declaration, else its vendor's; None = unchecked."""
    if me is None:
        return None
    if me.o1_adaptor_endpoint_id is not None:
        endpoint = db.get(O1AdaptorEndpoint, me.o1_adaptor_endpoint_id)
        if endpoint is not None and endpoint.supported_services is not None:
            return endpoint.supported_services
    cap = vendor_capability(db, me)
    return cap.supported_services if cap is not None else None


def require_service(db: Session, managed_element_ref: str, service: str) -> None:
    """Axis-2 guard: refuse an O1 operation the ME's vendor doesn't implement."""
    services = effective_services(db, db.get(ManagedEntity, managed_element_ref))
    if services is not None and service not in services:
        raise framework_error(FrameworkError.O1_SERVICE_NOT_SUPPORTED,
                              detail=f"{managed_element_ref} does not support MnS service {service} (supports {services})")


def _allowed_classes(db: Session, cap: VendorCapability) -> dict[str, dict] | None:
    """The class and attribute descriptors a vendor's conformance mode allows: the spec descriptor (not for OWN), with the vendor's own classes and attributes merged over it (not for SPEC). None when neither is available, which means the vendor is not checked.
    """
    spec = _descriptor(db, cap.spec_schema_name, cap.spec_schema_revision) if cap.conformance_mode != "OWN" else None
    own = _descriptor(db, cap.schema_name, cap.schema_revision) if cap.conformance_mode != "SPEC" else None
    if spec is None and own is None:
        return None
    classes: dict[str, dict] = {ioc: dict(attrs) for ioc, attrs in (spec or {}).get("classes", {}).items()}
    for ioc, attrs in (own or {}).get("classes", {}).items():  # COMBINED: the vendor's named augments
        classes.setdefault(ioc, {}).update(attrs)
    return classes


def change_class(change: dict) -> str | None:
    """The IOC class a change targets: its explicit `className`, else the class of the last RDN of its `managedFunctionRef` DN, else None (a flat function id names no class).
    """
    if change.get("className"):
        return change["className"]
    return leaf_class(change.get("managedFunctionRef"))  # SA-RANOAM-4: the last RDN of a DN


def schema_problems(db: Session, change: dict) -> list[str]:
    """Axis-3 check: the change's class/attributes/values against the
    descriptor(s) its vendor's conformance mode selects."""
    me = db.get(ManagedEntity, change["managedElementRef"])
    cap = vendor_capability(db, me)
    if cap is None:
        return []
    classes = _allowed_classes(db, cap)
    if classes is None:
        return []
    where = f"{change['managedElementRef']} ({cap.vendor_name}, {cap.conformance_mode})"
    ioc = change_class(change)
    if ioc is not None and ioc not in classes:
        return [f"{where}: class {ioc} is not in the vendor's data model"]
    problems = []
    for attr, value in (change.get("attributeChanges") or {}).items():
        if ioc is not None:
            spec = classes[ioc].get(attr)
        else:
            spec = next((a[attr] for a in classes.values() if attr in a), None)
        if spec is None:
            problems.append(f"{where}: attribute {attr} is not defined" + (f" on {ioc}" if ioc else " on any class"))
        else:  # SB-5.2: the leaf's type, range, length, pattern, fraction digits and enum, before anything is dispatched
            reason = check_value(spec, value)
            if reason is not None:
                problems.append(f"{where}: {attr}={value!r} {reason}")
    return problems


def check_vendor_mode(db: Session, vendor_name: str | None, o1_protocol: str) -> None:
    """Refuses (409 PROTOCOL_NOT_SUPPORTED) an element whose `o1_protocol` is not among the O1 modes its vendor declared. Nothing is checked for an element with no vendor or a vendor with no capability entry.
    """
    cap = db.get(VendorCapability, vendor_name) if vendor_name else None
    if cap is not None and PROTOCOL_MODE.get(o1_protocol) not in cap.supported_vendor_modes:
        raise framework_error(FrameworkError.PROTOCOL_NOT_SUPPORTED,
                              detail=f"vendor {vendor_name!r} declares {cap.supported_vendor_modes}, not {PROTOCOL_MODE.get(o1_protocol, o1_protocol)}")


# ---------------------------------------------------------------- managed entities + cell guards (W9-06)

# Request body of `PUT .../cells/{cell_id}/guards`: the attributes other rApps read before acting on a cell (class, sector group, incident zone, neighbours). The whole record is replaced.
class CellGuardBody(BaseModel):
    model_config = ConfigDict(extra="forbid")
    cellClass: CellClass = "NORMAL"
    sectorGroup: str | None = None
    incidentZone: str | None = None
    neighbourRefs: list[str] = []


def _get_me(db: Session, managed_element_ref: str) -> ManagedEntity:
    me = db.get(ManagedEntity, managed_element_ref)
    if me is None:
        raise framework_error(FrameworkError.MANAGED_ENTITY_NOT_FOUND, detail=f"no managed entity {managed_element_ref!r}")
    return me


def _me_view(db: Session, me: ManagedEntity) -> dict:
    """The JSON view of a managed element, including its effective MnS services, the vendor's conformance mode, its cell guards, and its region and tenant.
    """
    cap = vendor_capability(db, me)
    return {"managedElementRef": me.managed_element_ref, "managedFunctionRef": me.managed_function_ref,
            "entityType": me.entity_type, "vendorName": me.vendor_name, "o1Protocol": me.o1_protocol,
            "o1AdaptorEndpointId": str(me.o1_adaptor_endpoint_id) if me.o1_adaptor_endpoint_id else None,
            "supportedServices": effective_services(db, me), "conformanceMode": cap.conformance_mode if cap else None,
            "cellGuards": me.cell_guards or {}, "region": me.region, "tenant": me.tenant, "siteCluster": me.site_cluster}


@router.get("/managed-entities")
def list_managed_entities(request: Request, vendor_name: str | None = None, region: str | None = None, tenant: str | None = None,
                          site_cluster: str | None = None, search: str | None = Query(None, min_length=1, max_length=200),
                          limit: int = PageLimit, offset: int = PageOffset, db: Session = Depends(get_session)):
    """The registered managed elements. `region` and `tenant` narrow the list (PR-SEC-10.2), and `site_cluster` (PR-GUI-9.8). `search` (PR-GUI-9.2)
    keeps the elements whose managed element ref or managed function ref contains it, ignoring case. A caller with a scope claim sees only the elements
    inside it (PR-SEC-10.6: the list is filtered, never refused)."""
    stmt = scoping.scoped_to_elements(select(ManagedEntity), scoping.request_scope(request), ManagedEntity.managed_element_ref).order_by(ManagedEntity.managed_element_ref)
    stmt = msac.readable(stmt, db, request, ManagedEntity.managed_element_ref)                       # MGT-2.6: the elements the caller's access rules do not let it read are left out
    if region:
        stmt = stmt.where(ManagedEntity.region == region)
    if tenant:
        stmt = stmt.where(ManagedEntity.tenant == tenant)
    if vendor_name:
        stmt = stmt.where(ManagedEntity.vendor_name == vendor_name)
    if site_cluster:
        stmt = stmt.where(ManagedEntity.site_cluster == site_cluster)
    if search:
        # autoescape: a `%` or `_` the caller typed is a character to find, not a wildcard
        needle = search.lower()
        stmt = stmt.where(func.lower(ManagedEntity.managed_element_ref).contains(needle, autoescape=True)
                          | func.lower(func.coalesce(ManagedEntity.managed_function_ref, "")).contains(needle, autoescape=True))
    page = paginate(db, stmt, limit, offset)
    return {**page, "items": [_me_view(db, me) for me in page["items"]]}


@router.get("/managed-entities/{managed_element_ref}")
def get_managed_entity(managed_element_ref: str, request: Request, db: Session = Depends(get_session)):
    # Scope first: 403 SCOPE_DENIED when the caller's scope does not cover the element (also for an unregistered one); then 404 MANAGED_ENTITY_NOT_FOUND. The MSAC read rules of MGT-2 are applied to the list, not here.
    scoping.require_elements(db, scoping.request_scope(request), [managed_element_ref])       # PR-SEC-10.5: 403 SCOPE_DENIED outside the caller's scope
    return _me_view(db, _get_me(db, managed_element_ref))


class ScopeBody(BaseModel):
    """Where an element is and whom it belongs to (PR-SEC-10.2): `null` clears it. Both keys replace the stored values."""
    model_config = ConfigDict(extra="forbid")
    region: str | None = Field(default=None, max_length=100)
    tenant: str | None = Field(default=None, max_length=100)

    @field_validator("region", "tenant")
    @classmethod
    def _valid(cls, value: str | None) -> str | None:
        if value is not None and not authz_scope.valid_value(value):
            raise ValueError("must be 1 to 100 characters of letters, digits and . _ : / @ + -, starting with a letter or digit")
        return value


@router.put("/managed-entities/{managed_element_ref}/scope")
def set_managed_entity_scope(managed_element_ref: str, body: ScopeBody, db: Session = Depends(get_session)):
    """PR-SEC-10.2: set the `region` and `tenant` of a managed element (an operator's or an SMO module's call; an rApp is refused at the gateway). Replaces both;
    a key left out or `null` clears it, and an element with no region (tenant) is then for unscoped callers, and for callers whose claim does not restrict
    regions (tenants), only. Takes effect on the next request. 404 for an unknown element."""
    me = _get_me(db, managed_element_ref)
    me.region, me.tenant = body.region, body.tenant
    db.commit()
    return {"managedElementRef": me.managed_element_ref, "region": me.region, "tenant": me.tenant}


@router.put("/managed-entities/{managed_element_ref}/cells/{cell_id}/guards")
def set_cell_guards(managed_element_ref: str, cell_id: str, body: CellGuardBody, request: Request, db: Session = Depends(get_session)):
    # 403 SCOPE_DENIED outside the caller's scope, 404 for an unknown element. Replaces the whole guard record of that cell (other cells are kept) and commits; the cell id is not checked against the element's cells.
    scoping.require_elements(db, scoping.request_scope(request), [managed_element_ref])        # PR-SEC-10.9: 403 SCOPE_DENIED outside the caller's scope
    me = _get_me(db, managed_element_ref)
    me.cell_guards = {**(me.cell_guards or {}), cell_id: body.model_dump()}  # reassign: JSON columns don't track in-place edits
    db.commit()
    return {"managedElementRef": managed_element_ref, "cellId": cell_id, **body.model_dump()}


@router.delete("/managed-entities/{managed_element_ref}/cells/{cell_id}/guards", status_code=204)
def delete_cell_guards(managed_element_ref: str, cell_id: str, request: Request, db: Session = Depends(get_session)):
    # 403 SCOPE_DENIED outside the caller's scope, 404 for an unknown element; 204 whether or not the cell had a guard record.
    scoping.require_elements(db, scoping.request_scope(request), [managed_element_ref])        # PR-SEC-10.9: 403 SCOPE_DENIED outside the caller's scope
    me = _get_me(db, managed_element_ref)
    if cell_id in (me.cell_guards or {}):
        me.cell_guards = {k: v for k, v in me.cell_guards.items() if k != cell_id}
        db.commit()


@router.get("/cell-guards")
def query_cell_guards(request: Request, managed_element_ref: str | None = None, cell_id: str | None = None, cell_class: CellClass | None = None,
                      sector_group: str | None = None, incident_zone: str | None = None, region: str | None = scoping.RegionFilter,
                      site_cluster: str | None = scoping.SiteClusterFilter, limit: int = PageLimit,
                      offset: int = PageOffset, db: Session = Depends(get_session)):
    """The guard query any rApp uses (e.g. the EnergySaving rApp never
    sleeps an EMERGENCY cell, nor two cells of one sectorGroup at once). PR-SEC-10.6: only the elements inside the caller's scope claim.
    PR-GUI-9.3: `region` and `site_cluster` keep the cells of the elements of that place."""
    stmt = scoping.scoped_to_elements(select(ManagedEntity), scoping.request_scope(request), ManagedEntity.managed_element_ref).order_by(ManagedEntity.managed_element_ref)
    stmt = scoping.narrowed_to_place(stmt, ManagedEntity.managed_element_ref, region, site_cluster)
    stmt = msac.readable(stmt, db, request, ManagedEntity.managed_element_ref)                       # MGT-2.6
    if managed_element_ref:
        stmt = stmt.where(ManagedEntity.managed_element_ref == managed_element_ref)
    items = []
    for me in db.scalars(stmt):
        for cid, guard in sorted((me.cell_guards or {}).items()):
            if (cell_id and cid != cell_id) or (cell_class and guard["cellClass"] != cell_class) \
                    or (sector_group and guard.get("sectorGroup") != sector_group) \
                    or (incident_zone and guard.get("incidentZone") != incident_zone):
                continue
            items.append({"managedElementRef": me.managed_element_ref, "cellId": cid, **guard})
    return paginate_list(items, limit, offset)
